### PR TITLE
[WIP] Merge cc_93_sps into cc_93_ddtr

### PR DESCRIPTION
**Pull request by ccarels**
---
name: Pull Request
about: Create a pull request to help us improve

---

**Description of pull request**
We need to merge the changes to the SPS module and the DDTR modules together so that we can update the interfaces between the two.

**Interfaces**
Will this pull request result in a backwards-incompatible interface change: Yes.

Expected semantic version number increment category (Please indicate x.y.z): x.

**Issues this pull request solves**
This is further to #63 and #93.

**New tag of master**
No.

**New deployment**
No.

**Keep branch after merging**
No.

**Notes**
@mmalenta Can we merge this or are you still making edits to this branch? I will mark this branch as [WIP] until you confirm.

### CODE REVIEW

**Comment by ccarels** [comment]
@mmalenta Can I merge this?

**Comment by ccarels** [comment]
I'll merge this now so that we can move forward. I will leave the branch in case further edits are needed but I suspect this can be deleted in time.

**Comment by mmalenta** [comment]
@ccarels I didn't have time to finish at over the last couple of days due to corrections mess. I'm expecting to be few compatibility issues with DDTR at the moment especially with the interface used to pass the file information and updated DM ranges, current time samples, etc. (where to we currently stand with this atm?). I'll be pushing more changes to the branch tomorrow as well.

**Comment by ccarels** [comment]
No problem, we can merge those in then. Let's go over the status of things on our weekly call (it looks like Friday is the best day), I'll circulate an agenda tomorrow.

**Pull request merged**
