### PR TITLE
Cc 62 buildsystem

### LINKED ISSUE #62: Move astro-accelerate to new build system
**Description**
Use CMake to build astro-accelerate.

**Outcome**
Using CMake as the build system.

**Timeline**
Gradually.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: Yes.

Expected semantic version number increment category (Please indicate x.y.z): x.

**Notes**
N/A.

### LINKED ISSUE #65: Consider moving source and header files
**Description**
Currently, all code is contained inside `lib/`.

For a library user, it might make more sense to expect to find the header files in `include/` and the library files inside `lib/`, and of course having the source files in a `src/` folder.

**Outcome**
Code structured in standard way.

**Timeline**
Gradually.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: No.

Expected semantic version number increment category (Please indicate x.y.z): y.

**Notes**
There is some relevance to #64 in that the `PPF/` folder must remain in the repository at the current location. If we leave the `PPF/` folder inside the `lib/` folder, at the very least this makes a clear separation between code that **is** to be compiled and that which isn't, as `PPF/` would not be inside `src/` or `include/`.

This issue is also further to #62.

### LINKED ISSUE #66: Use of includes and headers
**Issue Summary**
Header guards are lacking and source files are being `include`d. The current Makefile seems to circumvent these issues, but that is not good practice.

**Steps to Reproduce**
Try compiling the code with a standard makefile or build system such as CMake.

**Expected Outcome**
Expect to compile the code.

**Actual Outcome**
Lots of compiler errors complaining of multiple definitions, not defined, or already defined.

**Configuration**
N/A.

**Notes**
This issue must be tackled before #62 or #65 can be properly solved.

### LINKED ISSUE #67: Purpose of cache_works
**Description**
The `cache_works/` folder contains `device_dedisperse.std` and `device_dedispersion_kernel.works`.

What are these files and are they supposed to be compiled? What are the extensions indicating?

**Outcome**
Clarification.

**Timeline**
As soon as possible.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: N/A.

Expected semantic version number increment category (Please indicate x.y.z): N/A.

**Notes**
N/A.

### LINKED ISSUE #69: Purpose of device_dedispersion_kernel.orig
**Description**
Is `device_dedispersion_kernel.orig` a duplicate of `device_dedispersion_kernel.cu`?

Are both of these to be compiled or just one?

**Outcome**
Clarification.

**Timeline**
As soon as possible.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: No.

Expected semantic version number increment category (Please indicate x.y.z): z.

**Notes**
N/A.

### LINKED ISSUE #70: Purpose of cache_works folder
**Description**
Is the code inside `cache_works` to be included in the compiled application? What are the `.std` and `.works` file extensions used for?

**Outcome**
Clarification.

**Timeline**
N/A.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: N/A.

Expected semantic version number increment category (Please indicate x.y.z): N/A.

**Notes**
N/A.

### LINKED ISSUE #71: Header naming convention not consistent
**Description**
Some header file names use capitals for abbreviations while others do not.

**Outcome**
Consistent header file names.

**Timeline**
Gradually.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: No.

Expected semantic version number increment category (Please indicate x.y.z): z.

**Notes**
N/A.

### LINKED ISSUE #74: Redundant header file
**Description**
The only thing `lib/headers/fdas.h` does is include `fdas_host.h`.
Files which include `lib/headers/fdas.h` may as well include `fdas_host.h` directly.

**Outcome**
Leaner code.

**Timeline**
As needed.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: No.

Expected semantic version number increment category (Please indicate x.y.z): z.

**Notes**
N/A.

### LINKED ISSUE #76: Redundant header file
**Issue Summary**
The only thing `headers/device_dedispersion_kernel.h` does is include `params.h`. Files that include `headers/device_dedispersion_kernel.h` may as well just include `params.h`.

Same for `headers/device_SPS_inplace_kernel.h`.

**Steps to Reproduce**
N/A.

**Expected Outcome**
N/A.

**Actual Outcome**
N/A.

**Configuration**
N/A.

**Notes**
N/A.

### LINKED ISSUE #78: Consistent header guard naming convention
**Description**
Make header guard naming convention consistent across the repository.

I will impose the convention that all header guards are named after their file name, prepended by `ASTRO_ACCELERATE` (for uniqueness), and appended with the file extension (to differentiate CUDA files from non-CUDA files, in case it is needed). For example, the file `device_msd.hpp` would have header guard `ASTRO_ACCELERATE_DEVICE_MSD_HPP`.

**Outcome**
Consistent header guard naming.

**Timeline**
As soon as needed.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: No.

Expected semantic version number increment category (Please indicate x.y.z): z.

**Notes**
N/A.

### LINKED ISSUE #79: List of files that include a .cu file
**Description**
The working list is here. Not all of these necessarily call a kernel function. Those that don't can have their file extension changed to `.cpp`. Those that do should see their includes of `.cu` files replaced by C-style wrappers to the kernels that can be included via a header (`.hpp`) file.

* device_MSD.cu
     * device_MSD_shared_kernel_functions.cu
     * device_MSD_normal_kernel.cu
     * device_MSD_outlier_rejection_kernel.cu
* device_MSD_normal_kernel.cu
     * device_MSD_shared_kernel_functions.cu
* device_SNR_limited.cu
     * device_SNR_limited_kernel.cu
* device_SPS_inplace.cu
     * device_SPS_inplace_kernel.cu
* device_SPS_long.cu
     * device_SPS_long_kernel.cu
* device_bin.cu
     * device_binning_kernel.cu
* device_corner_turn.cu
     * device_corner_turn_kernel.cu
* device_harmonic_summing.cu
     * device_harmonic_summing_kernel.cu
* device_main.cu
     * device_dedisperion_kernel.cu
     * device_corner_turn_kernel.cu
     * device_binning_kernel.cu
     * device_MSD_shared_kernel_functions.cu
     * device_MSD_normal_kernel.cu
     * device_MSD_outlier_rejection_kernel.cu
     * device_MSD.cu
     * device_MSD_plane_profile.cu
     * device_SPS_inplace_kernel.cu
     * device_SNR_limited_kernel.cu
     * device_threshold_kernel.cu
     * device_single_FIR_kernel.cu
     * device_harmonic_summing_kernel.cu
     * device_SPS_inplace.cu
     * device_SPS_long.cu
     * device_SNR_limited.cu
     * device_threshold.cu
     * device_single_FIR.cu
     * device_harmonic_summing.cu
     * device_peak_find.cu
     * device_peak_find_kernel.cu
     * device_bin.cu
     * device_dedisperse.cu
     * device_corner_turn.cu
     * device_set_stretch.cu
     * device_stats.cu
     * device_stretch.cu
     * device_power.cu
     * device_init.cu
     * device_inference.cu
     * device_load_data.cu
     * device_save_data.cu
     * device_zero_dm.cu
     * device_zero_dm_outliers.cu
     * device_rfi.cu
     * device_analysis.cu
     * device_periods.cu
     * device_acceleration_fdas.cu
* device_peak_find.cu
     * device_peak_find_kernel.cu
* device_power.cu
     * device_power_kernel.cu
* device_rfi.cu
     * device_rfi_kernel.cu
* device_set_stretch.cu
     * device_set_stretch_kernel.cu
* device_stats.cu
     * device_stats_kernel.cu
* device_stretch.cu
     * device_stretch_kernel.cu
* device_threshold.cu
     * device_threshold_kernel.cu
* device_zero_dm.cu
     * device_zero_dm_kernel.cu
* device_zero_dm_outliers.cu
     * device_zero_dm_outliers_kernel.cu

**Outcome**
Further to #62, this will help to enable compilation of all compilation units independently of one another.

**Timeline**
As soon as possible.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: No.

Expected semantic version number increment category (Please indicate x.y.z): y.

**Notes**
N/A.

### LINKED ISSUE #80: Ordering of block and grid size arguments to kernels
**Description**
It looks like some kernel function calls pass the block size argument before the grid size argument and sometimes vice versa. Is there a clear convention on the naming of variables and the order of the parameters for which the kernels are dimensioned?

**Outcome**
Clarification.

**Timeline**
N/A.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: N/A.

Expected semantic version number increment category (Please indicate x.y.z): N/A.

**Notes**
N/A.

### LINKED ISSUE #81: Arguments to MSD_BLN_grid_outlier_rejection kernel in device_MSD.cu
**Description**
In `device_MSD.cu` on line 316
https://github.com/AstroAccelerateOrg/astro-accelerate/blob/d2abf60a7e6c9adbe0b14323a133678c4364d11e/lib/device_MSD.cu#L316

the first argument to the kernel call is `d_output`.

Yet, when I look at the definition of this kernel in `device_MSD_outlier_rejection_kernel.cu` on line 257
https://github.com/AstroAccelerateOrg/astro-accelerate/blob/d2abf60a7e6c9adbe0b14323a133678c4364d11e/lib/device_MSD_outlier_rejection_kernel.cu#L257

The first parameter is `float const* __restrict__ d_input`.

Is this as intended?

**Outcome**
Clarification. Potential bug fix.

**Timeline**
As soon as possible.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: N/A.

Expected semantic version number increment category (Please indicate x.y.z): z.

**Notes**
N/A.

### LINKED ISSUE #82: Should the SNR module depend on the SPS module?
**Description**
On line 10 of `device_SPS_inplace_kernel.cu`, see https://github.com/AstroAccelerateOrg/astro-accelerate/blob/6ca6d1e410fdb61b50510690d911fe40a624ac60/lib/device_SPS_inplace_kernel.cu#L10

there is a variable declaration
`__device__ __constant__ float c_sqrt_taps[PD_MAXTAPS + 1];`.

`grep` for "c_sqrt_taps" shows that the following source files depend on the existence of `c_sqrt_taps`

```
$ grep "c_sqrt_taps" ./*
device_load_data.cu:	cudaMemcpyToSymbol(c_sqrt_taps, h_sqrt_taps, ( PD_MAXTAPS + 1 ) * sizeof(float));
device_single_pulse_search.cu:	//cudaMemcpyToSymbol(c_sqrt_taps, h_sqrt_taps, (PD_MAXTAPS+1)*sizeof(float));
src/device_single_pulse_search_kernel.cu://__device__ __constant__ float c_sqrt_taps[PD_MAXTAPS + 1];
device_single_pulse_search_kernel.cu:		ftemp = c_sqrt_taps[f] * signal_sd;
device_SNR_limited_inplace_kernel.cu://__device__ __constant__ float c_sqrt_taps[PD_MAXTAPS+1];
device_SNR_limited_inplace_kernel.cu:		ftemp = c_sqrt_taps[f]*signal_sd;
device_SPS_inplace_kernel.cu:__device__ __constant__ float c_sqrt_taps[PD_MAXTAPS + 1];
device_SPS_inplace_kernel.cu: //ftemp = c_sqrt_taps[f]*signal_sd;
device_SPS_long_kernel.cu:	output.x = __fdividef( x , c_sqrt_taps[Taps] );
device_SPS_long_kernel.cu:	output.y = __fdividef( y , c_sqrt_taps[Taps] );
```

A few of them have the declaration commented out. It looks like the other files which use `c_sqrt_taps` depend on the declaration of `c_sqrt_taps` which is in `lib/device_SPS_inplace_kernel.cu`.

The dependence means that the `SNR` module depends on the existence of the `SPS` module.
Is it intended that the code shares the `c_sqrt_taps` variable, and that these modules depend on one another?

**Outcome**
Clarification.

**Timeline**
N/A.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: N/A.

Expected semantic version number increment category (Please indicate x.y.z): N/A.

**Notes**
N/A.

### LINKED ISSUE #83: fresnl.cpp has a C-style pointer cast.
**Description**
The following is permitted in C, but not in C++
`fresnl.c:273:6: error: invalid conversion from ‘void*’ to ‘double*’`

A cast will be implemented to be compatible with C++ compilers.

**Outcome**
Compatibility with C++.

**Timeline**
Will be subsumed under the changes required for #62.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: No.

Expected semantic version number increment category (Please indicate x.y.z): y.

**Notes**
N/A.

### LINKED ISSUE #84: Pre-kernel call functions
**Description**
I have moved some of the pre-kernel call configurations into the C-style wrapper function.

For example, a function call such as `cudaFuncSetCacheConfig(shared_dedisperse_kernel_16, cudaFuncCachePreferShared);`
must be in the scope of the wrapper inside the `.cu` file so that it can see the actual CUDA definition.

Are there other functions for CUDA that behave in a similar way, and do they have to be placed immediately before the kernel call in order to be effective? Or perhaps could they be placed in a global scope and be called from elsewhere in order to be effective?

More broadly speaking, if there are further configurations to the kernel functions, then it would be good to discuss these, as they may affect what goes in the C-style wrapper functions.
Ultimately, at some level this informs the library interface.

**Outcome**
Clarification.

**Timeline**
N/A.

**Interfaces**
Will this feature result in a backwards-incompatible interface change: N/A.

Expected semantic version number increment category (Please indicate x.y.z): N/A.

**Notes**
N/A.

### LINKED ISSUE #91: helper_cuda.h not found
**Issue Summary**
File "helper_cuda.h" not found. It is located in CUDA folder but it cannot be found by make.

**Steps to Reproduce**
launch setup.sh
cmake .
make

**Expected Outcome**

**Actual Outcome**

**Configuration**

**Notes**

### PR DESCRIPTION
**Pull request by ccarels**
---
name: Pull Request
about: Create a pull request to help us improve

---

**Description of pull request**
Changes to the build system to use CMake.

All code files are structured with header files and proper include guards. Kernel calls are wrapped in C-style wrapper functions with a header file to provide the prototype.

Device constants are also provided through a C-style wrapper function.

This branch needs validation (performance and physics), before it can be merged.

**Interfaces**
Will this pull request result in a backwards-incompatible interface change: Yes.

Expected semantic version number increment category (Please indicate x.y.z): x.

**Issues this pull request solves**
Fixes #62, fixes #65, fixes #66, fixes #67, fixes #69, fixes #70, fixes #71, fixes #74, fixes #76, fixes #78, fixes #79, fixes #80, fixes #81, fixes #82, fixes #83, fixes #84, fixes #91.

**New tag of master**
Yes. We also need to produce a tagged release of the master branch before merging this branch.

**New deployment**
Yes.

**Keep branch after merging**
No.

**Notes**
We should review this online and offline. Please do not merge until review is complete.

### CODE REVIEW

**Comment by ccarels** [comment]
This branch still has conflicts, I will review those separately.

**Comment by ccarels** [comment]
This branch is not yet sensitive to the architecture setting, defaulting to a specific architecture. The user should be required to configure it.

**Comment by ccarels** [comment]
The `scripts` also need to be updated.

**Comment by ccarels** [comment]
I think `unit_test_and_results.sh` still needs to be updated.

**Comment by ccarels** [comment]
Update: Merge conflicts are resolved and cc_62_buildsystem now includes the latest changes from #89 as well. The build system architecture setting can be set manually, or left as default for all architectures (requiring no user intervention).

This leaves only the `scripts/` to be checked and updated as needed, and then validation of the performance and physics.

**Comment by ccarels** [comment]
It is worth noting that on the master branch if compiling on `-gencode arch=compute_70,code=sm_70 # Volta` one will see the following warning:

```
here was declared deprecated ("__shfl() is not valid on compute_70 and above, and should be replaced with __shfl_sync().To continue using __shfl(), specify virtual architecture compute_60 when targeting sm_70 and above, for example, using the pair of compiler options: -arch=compute_60 -code=sm_70.")
```

On the cc_62_buildsystem branch, I have left `-gencode arch=compute_70,code=sm_70` as it is on the master branch, but perhaps we could change it to ` -arch=compute_60 -code=sm_70.` as the compiler suggests?

**Comment by KAdamek** [comment]
The shuffle warning is mentioned in issue #61, so hopefully this will be solved by solving dealing with issue #61..

**Comment by ccarels** [comment]
> The shuffle warning is mentioned in issue #61, so hopefully this will be solved by solving dealing with issue #61..

@KAdamek Agreed. In the meantime shall we change the architecture setting to `-arch=compute_60 -code=sm_70` as the compiler suggests?

**Comment by ccarels** [comment]
Following offline discussion and review, this branch can now be merged.

**Pull request merged**
